sources:
  - Kantumruy.glyphs
  # - Rubik-Italic.glyphs
axisOrder:
  - wght
  # - ital
familyName: Kantumruy
instances:
  Kantumruy-Thin.otf:
    - coordinates:
        wght: 16
  Kantumruy-Regular.otf:
    - coordinates:
        wght: 80